### ISSUE TITLE
HTTP 413 message (improvement idea)

### ISSUE THREAD

**Issue by kaestli** [EIDA/mediatorws#118]
For the federator (dataselect, wfcatalog), thresholds for http 413 ("request too large" - actually meaning: response too large) are defined in stream days. It would be helpful for the user if in a http 413 response, the currently configured limit for the requested service is mentioned - it would allow him/her relatively easily to tailor request in a way to avoid meeting http 413 in future...

**Comment by damb** [comment]
For all resources HTTP status code 413 is returned as well if the size of the POST body size exceeds certain limits.
