### ISSUE TITLE
provide some landing page for endpoint URL ...

### ISSUE THREAD

**Issue by petrrr** [EIDA/mediatorws#120]
This is a minor issue but also quite easy to fix.

I would suggest to provide some simple page for the following URL:
* http://eida-federator.ethz.ch/fdsnws/station/1/

For example a swagger pages, a description of the service or a builder.

Currently it provides a Status code 404. Not nice! Especially because this URL is pointed at by Orfeus.

**Comment by damb** [comment]
I didn't implement a landing page, yet.

Adding OpenAPI3 to FDSNWS was discussed during one of our last ETC meetings, anyway. IMO a good idea.

**Comment by damb** [comment]
Fixed with https://github.com/damb/eidaws/commit/7d24e767d34c98b454c7bc78401947dadcf7dcfb. Thanks again for pointing this out.
