### ISSUE TITLE
granular endpoint requests

### ISSUE THREAD

**Issue by kaestli** [EIDA/mediatorws#15]
issue one individual request for each stream epoch (as returned by stationlite)

**Comment by damb** [comment]
**Issue:** granular endpoint requests for `FDSN/station` currently would lead to duplicated data for `level=network|station`. Combiners currently do not have a *deduplicated* mode.

**Comment by damb** [comment]
The current splitting mechanism does not handle large requests for e.g. `dataselect`. Currently *federator* splitting is implemented by dividing the number of *postline requests*. However, for granular requests splitting must be implemented by means of splitting stream epochs regarding time constraint parameters.

**Comment by damb** [comment]
Implemented with ae4582a3959851ceda9e7e1b0a84df6dffd2d05c. See also #29.
