### ISSUE TITLE
Starttime & endtime format

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#2]
Hi guys, here is a little issue. Starttime and endtime must always be given a time or the response will be 204 No Content. It should either just assume 00:00:00 if left blank (preferable) or return 400 Bad Request.

    mediator-devel.ethz.ch/fdsnws/dataselect/1/query?net=NL&sta=HGN&start=2016-01-01T00:00:00&end=2016-01-02T00:00:00
    >>> returns 200

    mediator-devel.ethz.ch/fdsnws/dataselect/1/query?net=NL&sta=HGN&start=2016-01-01&end=2016-01-02
    >>> returns 204

Best,
Mathijs

**Comment by feuchner** [comment]
This was due to the fact that the routing services requires timestamps including the time part. Fixed in 93517356c44b1e2875029272ace06765b1f3fdcd.
