### ISSUE TITLE
StationXML query 204

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#27]
Requests for node INGV returns 204:

    http://mediator-devel.ethz.ch/fdsnws/station/1/query?network=IV

Maybe because of the `xmlns:ingv` namespace?

**Comment by damb** [comment]
Hi Philipp,
THIS IS A REMINDER :)

cheers, Daniel

**Comment by damb** [comment]
Hi @Jollyfant,

the Federator should be able to handle the `xmlns:ingv` namespace.

However, it seems to be an endpoint configuration issue. Even though I decreased already the number of parallel requests to 5 I receive HTTP status code **429** (Too many requests. By the way this is no valid FDSNWS HTTP status code.)

With pleasure I'd like to check the maximum number of parallel requests, but now the federator seems to be blocked by `fail2ban`. And after more than half an hour it is still blocked ...

cheers

**Comment by Jollyfant** [comment]
@damb are you in the EIDA mailing list? We can discuss the issue there. Also, I think RESIF has a custom XML namespace that needs to be included (if its not handled automatically already). The 429 status code for the Federator means the IP(s) running the Federator service(s) should be whitelisted.

We should really look in to improving the endpoints eventually.

**Comment by damb** [comment]
As the topic moved to `eida_maint` mailing list I close this ticket here.
