### ISSUE TITLE
Incomplete response

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#3]
Hi, there is a difference in requesting from the node directly or through the federator:

    mediator-devel.ethz.ch/fdsnws/dataselect/1/query?net=NL&sta=HGN&start=2016-01-01T00:00:00&end=2016-01-02T00:00:00
    >>> Content-Length: 422 kB

    orfeus-eu.org/fdsnws/dataselect/1/query?net=NL&sta=HGN&start=2016-01-01&end=2016-01-02
    >>> Content-Length: 14.1 MB

Federator only seems to return one channel:

    NL.HGN.02.BHZ | 2015-12-31T23:59:59.544538Z - 2016-01-01T02:20:30.944538Z | 40.0 Hz, 337257 samples

While our services gives multiple:

    NL.HGN.02.BHZ | 2015-12-31T23:59:59.544538Z - 2016-01-01T02:20:30.944538Z | 40.0 Hz, 337257 samples
    NL.HGN.02.BHZ | 2016-01-01T02:20:31.044500Z - 2016-01-01T02:20:31.044500Z | 40.0 Hz, 0 samples
    NL.HGN.02.BHZ | 2016-01-01T02:20:30.969538Z - 2016-01-01T02:20:55.869538Z | 40.0 Hz, 997 samples
    NL.HGN.02.BHZ | 2016-01-01T02:20:56.344500Z - 2016-01-01T02:20:56.344500Z | 40.0 Hz, 0 samples
    NL.HGN.02.BHZ | 2016-01-01T02:20:55.894538Z - 2016-01-02T00:00:06.769538Z | 40.0 Hz, 3118036 samples
    NL.HGN.02.LHZ | 2015-12-31T23:59:34.069538Z - 2016-01-01T02:21:12.069538Z | 1.0 Hz, 8499 samples
    NL.HGN.02.LHZ | 2016-01-01T02:20:43.069500Z - 2016-01-01T02:20:43.069500Z | 1.0 Hz, 0 samples
    NL.HGN.02.LHZ | 2016-01-01T02:21:13.069538Z - 2016-01-01T04:21:55.069538Z | 1.0 Hz, 7243 samples
    NL.HGN.02.LHZ | 2016-01-01T04:21:17.069500Z - 2016-01-01T04:21:17.069500Z | 1.0 Hz, 0 samples
    NL.HGN.02.LHZ | 2016-01-01T04:21:56.069538Z - 2016-01-01T15:21:05.069538Z | 1.0 Hz, 39550 samples
    NL.HGN.02.LHZ | 2016-01-01T15:22:21.069500Z - 2016-01-01T15:22:21.069500Z | 1.0 Hz, 0 samples
    NL.HGN.02.LHZ | 2016-01-01T15:21:06.069539Z - 2016-01-02T00:00:22.069539Z | 1.0 Hz, 31157 samples
    NL.HGN.02.BHE | 2015-12-31T23:59:58.094538Z - 2016-01-02T00:00:00.844538Z | 40.0 Hz, 3456111 samples
    NL.HGN.02.LHE | 2015-12-31T23:59:15.069538Z - 2016-01-02T00:02:35.069538Z | 1.0 Hz, 86601 samples
    NL.HGN.02.LHN | 2015-12-31T23:57:44.069539Z - 2016-01-02T00:01:31.069539Z | 1.0 Hz, 86628 samples
    NL.HGN.02.BHN | 2015-12-31T23:59:55.819538Z - 2016-01-02T00:00:00.144538Z | 40.0 Hz, 3456174 samples

Best,
Mathijs

**Comment by feuchner** [comment]
This was because of insufficient handling of mseed records with zero 'beginning of data' in fixed header. Fixed in d3e77ffbb8022a50157eeb010ff5bf862dcabc34.
