### ISSUE TITLE
Request with non-capital letter returns bad request

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#34]
Try:

    http://federator-testing.ethz.ch/fdsnws/station/1/query?net=Nl

**Comment by damb** [comment]
I know, but this was implemented intentionally. I'm not completely aware of the EIDA `SNCL` naming convention. However, with your suggestion this would mean

```
Nl == NL
```

Hence, in case a `Nl` network is defined this would inevitably lead to errors, right?

**Comment by Jollyfant** [comment]
I would think it returns a 204 if you query and end point. Nl is not equivalent to NL

**Comment by kaestli** [comment]
There is no further standardization statement on network codes beyond the fact that it is 1 or 2 letters, alphanumeric, and parts of the name space are reserved for temporary networks (with non-unique codes). There is no statement (neither on the FDSN website nor in SEED appendix J) disallowing for non-capital network codes, or stating that capital and non-capital letters are to be treeated as equal.
Also for channel codes (a bit better defined SEED manual appendix A), there is no statement which either disallows for non-capital codes or sets ABC=abc.
However, as all channel codes defined in appendix A, and all networks registered at http://www.fdsn.org/networks/ are in capital letters, users assuming ABC=abc have not terribly failed yet. Thus many users may expect the equality to be given.. 
It would, by the way, be a creative solution for the issues with name space limitation for networks in mseed, to take the seed standard by its word and start assigning network codes including non-capital letters...

**Comment by damb** [comment]
I'll implement a fix.
