### ISSUE TITLE
Configuration (Docker): StationLite routing

### ISSUE THREAD

**Issue by damb** [EIDA/mediatorws#37]
Continued discussion from `eida_maint` (see below):

@massimo1962 wrote:
>Many thanks for your help,
actually IFIK the stationlite rely on routing service in order to retrieve the
information and store into a db (sqlite). Consider that I have seen the load
db procedure works and fill the db ... so I have deduced that the routing
behind worked fine...  seem quite strange.
Moreover , consider that I have already do another installation (without
docker) and I have the same problem... o_0

@Jollyfant wrote:
>> Hi Massimo, I have the same problem. For me requests to the version paths work:
>>
>> `/fdsnws/station/1/version -> 1.1.0`
>>
>> but anything else is 500 Internal Server Error.
>>
>>In `/var/www/mediatorws/eidangservices/settings.py` I found a setting:
`EIDA_FEDERATOR_DEFAULT_ROUTING_URL` that points to ETH. But this routing
(stationLite?) service times out and is not reachable at all. It may be the
cause of the server error, so I tried changing it to localhost. But inside the
container I cannot seem to reach the stationLite service at all:
>>
>>`curl 0.0.0.0/eidaws/routing/1/version -> 404 Not Found`

@massimo1962 wrote:
>>> The point is: the services are up and running but every query (on federator)
that I do give me an empty response and error 500. I think it could be
something related to the stationlite service or something like that but, at
the moment, I can't figure out the problem. If someone can help me I will be
very happy.

**Comment by damb** [comment]
@Jollyfant,
thanks for the hint. Due to historical reasons the routing service used by `eida-federator` was configured using an optional CLI argument. In deed, the default parameter is set by `EIDA_FEDERATOR_DEFAULT_ROUTING_URL` (see: https://github.com/EIDA/mediatorws/blob/master/eidangservices/settings.py#L570-L571). Still `http://mediator-devel.ethz.ch/eidaws/routing/1/` is used which is not correct anymore.

Instead as a default parameter I suggest `http://localhost/eidaws/routing/1/`.

**Comment by Jollyfant** [comment]
Just for my clarification, that is the `stationlite` service that should be running inside the container right? Because I couldn't reach it under localhost there.

**Comment by damb** [comment]
@massimo1962,
I'm not an docker expert. However, it is not an `mediatorws` or rather `stationlite` issue, respectively, but a configuration issue of your delivery. What you're trying to do is the following (correct me please if I'm wrong):
1. You have a `base-eidang` Docker image
2. On top you have your `eidang_federator` image (image `eidang_federator` depends on `base-eidang`)

Within your `base-eidang` `Dockerfile` you install the basic dependencies, including Apache. So far, so good. Now to the `eidang_federator` image:

1. You install the webservices.
2. You configure Apache.

However, you use the exemplary Apache configuration files ([federator.conf](https://github.com/EIDA/mediatorws/blob/master/apache2/federator.conf) and [stationlite.conf](https://github.com/EIDA/mediatorws/blob/master/apache2/stationlite.conf).) Both define a Virtualhost configuration on port 80. When you run

```
## (apache enabling) ##
RUN a2ensite federator.conf

RUN a2ensite stationlite.conf
```
you first enable `eida-federator` on port 80. Then  `eida-stationlite` also on port 80. This simply does not work (Apache ignores `stationlite.conf`.). This is also the reason, why @Jollyfant isn't able to connect to `eida-stationlite`. Instead try a configuration as follows:

```
<VirtualHost *:80>

        ServerName mediatorws-test

        DocumentRoot /var/www/html

        <Directory /var/www/html>
                Order allow,deny
                Allow from all
        </Directory>

        # EIDA Federator Webservice
        WSGIDaemonProcess federator user=www-data group=www-data processes=10 threads=3 display-name=%{GROUP} python-home=/var/www/federator/venv

        # EIDA StationLite Webservice
        WSGIDaemonProcess stationlite user=www-data group=www-data  processes=5 threads=5 display-name=%{GROUP} python-home=/var/www/stationlite/venv
        WSGIScriptAlias /eidaws/routing /var/www/stationlite/apache2/stationlite.wsgi/eidaws/routing

        <Directory "/var/www/stationlite/apache2">
                WSGIProcessGroup stationlite
                WSGIApplicationGroup %{GLOBAL}
                WSGIScriptReloading On
                Order allow,deny
                Allow from all
        </Directory>

        #LogLevel info
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```
This example, however, assumes that you installed `federator` and `stationlite` into separate virtual environments. Simply adjust it as required.

cheers

**Comment by Jollyfant** [comment]
I changed the Apache configuration and stationlite doesn't want to start (Federator is OK).

    [Wed Jul 18 12:34:40.178989 2018] [wsgi:error] [pid 22:tid 139756298012416] USAGE ERROR: too few arguments
    [Wed Jul 18 12:34:40.185370 2018] [wsgi:error] [pid 22:tid 139756298012416] usage: eida-stationlite [-h] [-c PATH] [--version] [--start-local] [-p PORT]
    [Wed Jul 18 12:34:40.185415 2018] [wsgi:error] [pid 22:tid 139756298012416]                         [--logging-conf LOGGING_CONF]
    [Wed Jul 18 12:34:40.185429 2018] [wsgi:error] [pid 22:tid 139756298012416]                         URL
    [Wed Jul 18 12:34:40.185437 2018] [wsgi:error] [pid 22:tid 139756298012416] 
    [Wed Jul 18 12:34:40.185451 2018] [wsgi:error] [pid 22:tid 139756298012416] Launch EIDA stationlite web service.
    [Wed Jul 18 12:34:40.185520 2018] [wsgi:error] [pid 22:tid 139756298012416] 
    [Wed Jul 18 12:34:40.185539 2018] [wsgi:error] [pid 22:tid 139756298012416] positional arguments:
    [Wed Jul 18 12:34:40.185552 2018] [wsgi:error] [pid 22:tid 139756298012416]   URL                   DB URL indicating the database dialect and connection
    [Wed Jul 18 12:34:40.185562 2018] [wsgi:error] [pid 22:tid 139756298012416]                         arguments. For SQlite only a absolute file path is
    [Wed Jul 18 12:34:40.185569 2018] [wsgi:error] [pid 22:tid 139756298012416]                         supported.
    [Wed Jul 18 12:34:40.185578 2018] [wsgi:error] [pid 22:tid 139756298012416] 
    [Wed Jul 18 12:34:40.185583 2018] [wsgi:error] [pid 22:tid 139756298012416] optional arguments:
    [Wed Jul 18 12:34:40.185591 2018] [wsgi:error] [pid 22:tid 139756298012416]   -h, --help            show this help message and exit
    [Wed Jul 18 12:34:40.185602 2018] [wsgi:error] [pid 22:tid 139756298012416]   -c PATH, --config PATH
    [Wed Jul 18 12:34:40.185609 2018] [wsgi:error] [pid 22:tid 139756298012416]                         path to EIDA Webservice configuration file (default:
    [Wed Jul 18 12:34:40.185615 2018] [wsgi:error] [pid 22:tid 139756298012416]                         '/var/www/mediatorws/config/eidangws_config')
    [Wed Jul 18 12:34:40.185619 2018] [wsgi:error] [pid 22:tid 139756298012416]   --version, -V         show program's version number and exit
    [Wed Jul 18 12:34:40.185629 2018] [wsgi:error] [pid 22:tid 139756298012416]   --start-local         start a local WSGI server (not for production)
    [Wed Jul 18 12:34:40.185638 2018] [wsgi:error] [pid 22:tid 139756298012416]   -p PORT, --port PORT  server port (only considered when serving locally i.e.
    [Wed Jul 18 12:34:40.185647 2018] [wsgi:error] [pid 22:tid 139756298012416]                         with --start-local)
    [Wed Jul 18 12:34:40.185656 2018] [wsgi:error] [pid 22:tid 139756298012416]   --logging-conf LOGGING_CONF
    [Wed Jul 18 12:34:40.185666 2018] [wsgi:error] [pid 22:tid 139756298012416]                         path to a logging configuration file
    [Wed Jul 18 12:34:40.185766 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788] mod_wsgi (pid=22): Target WSGI script '/var/www/mediatorws/apache2/stationlite.wsgi' cannot be loaded as Python module.
    [Wed Jul 18 12:34:40.185789 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788] mod_wsgi (pid=22): SystemExit exception raised by WSGI script '/var/www/mediatorws/apache2/stationlite.wsgi' ignored.
    [Wed Jul 18 12:34:40.185836 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788] Traceback (most recent call last):
    [Wed Jul 18 12:34:40.185914 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]   File "/var/www/mediatorws/apache2/stationlite.wsgi", line 37, in <module>
    [Wed Jul 18 12:34:40.185986 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]     application = main()
    [Wed Jul 18 12:34:40.186012 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]   File "/usr/local/lib/python2.7/dist-packages/stationlite-0.9.2.2-py2.7.egg/eidangservices/stationlite/server/app.py", line 221, in main
    [Wed Jul 18 12:34:40.186061 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]     config_section=settings.EIDA_STATIONLITE_CONFIG_SECTION)
    [Wed Jul 18 12:34:40.186088 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]   File "/usr/local/lib/python2.7/dist-packages/federator-0.9.2.2-py2.7.egg/eidangservices/utils/app.py", line 159, in configure
    [Wed Jul 18 12:34:40.186129 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]     self.args = self.parser.parse_args(remaining_argv)
    [Wed Jul 18 12:34:40.186145 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]   File "/usr/lib/python2.7/argparse.py", line 1701, in parse_args
    [Wed Jul 18 12:34:40.186167 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]     args, argv = self.parse_known_args(args, namespace)
    [Wed Jul 18 12:34:40.186193 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]   File "/usr/lib/python2.7/argparse.py", line 1733, in parse_known_args
    [Wed Jul 18 12:34:40.186212 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]     namespace, args = self._parse_known_args(args, namespace)
    [Wed Jul 18 12:34:40.186225 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]   File "/usr/lib/python2.7/argparse.py", line 1950, in _parse_known_args
    [Wed Jul 18 12:34:40.186242 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]     self.error(_('too few arguments'))
    [Wed Jul 18 12:34:40.186255 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]   File "/usr/local/lib/python2.7/dist-packages/federator-0.9.2.2-py2.7.egg/eidangservices/utils/app.py", line 63, in error
    [Wed Jul 18 12:34:40.186331 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788]     sys.exit(ExitCodes.EXIT_ERROR)
    [Wed Jul 18 12:34:40.186376 2018] [wsgi:error] [pid 22:tid 139756298012416] [client 172.17.0.1:49788] SystemExit: 2

Also start locally fails:

    root@bebf59fba59c:/var/www/mediatorws/config# eida-stationlite --start-local -p 8080
USAGE ERROR: too few arguments

**Comment by damb** [comment]
Hi @Jollyfant,

`eida-stationlite -h` is your friend (you also have it in your logs):

```
[...]

positional arguments:
  URL              DB URL indicating the database dialect and connection
                       arguments. For SQlite only a absolute file path is 
                       supported.
[...]
```

When starting locally you need something like 

```
# eida-stationlite --logging-conf config/logging.conf -p 8080 --start-local sqlite:///`realpath db/stationlite.db`
```

**Comment by Jollyfant** [comment]
I don't want to start it locally but through WSGI.. that reading is from the Apache error log. I would assume it takes the default db file in

    /var/www/mediatorws/db

**Comment by Jollyfant** [comment]
Ok I commented out `#db_url` in `eidangws_config` and point to the sqlite database file. It shows me the version now :+1:.

Let's make it a default or put it in the README.

**Comment by damb** [comment]
@Jollyfant,

When using `mod_wsgi` (i.e. in production mode) the only way to provide the SQLite DB to `eida-stationlite` is by means of `eidaws_config`. More precisely you need something like:

```
# DB URL indicating the database dialect and connection arguments. For SQlite
# only a absolute file path is supported.
# See also:
# http://docs.sqlalchemy.org/en/latest/core/engines.html#database-urls
#
# db_url = sqlite:////abs/path/to/stationlite.db
db_url = sqlite:////var/www/stationlite/db/stationlite.db
```

**Background**:
`eida-stationlite` does not work without DB. That's why I used a required positional CLI parameter. Hence, it must be defined.

OK, I see you got it :+1: . Nice. I'll put it into the documentation.

cheers

**Comment by Jollyfant** [comment]
Now stationlite is giving me `500` but not Apache. I want to see stationlite log files. I point the service to the logging configuration file:

    /var/www/mediatorws/config/eidangws_config

And put this so it writes to file:

    [handler_consoleHandler]
    class=logging.StreamHandler
    level=DEBUG
    formatter=EidaFormatter
    args=('/var/www/mediatorws/config/', 'example.log', 'a')

Alas, nothing.

**Comment by damb** [comment]
@Jollyfant,

your logging configuration file is something different from `/var/www/mediatorws/config/eidangws_config`.

Your logging configuration file should be something like [logging.conf](https://github.com/EIDA/mediatorws/blob/master/config/logging.conf) if you'd like to write to `stdout` (In case you'd like to set it up with `mod_wsgi` I even would recommend you to use [syslog.conf](https://github.com/EIDA/mediatorws/blob/master/config/syslog.conf). (Adjust the configuration of your system logger accordingly. Exemplary `rsyslog` configrations you'll find [here](https://github.com/EIDA/mediatorws/tree/master/config)).)

Also, you should configure the path to your logging configuration file within your `eidangws_config`. (I recommend you to configure it both for `eida-federator` and `eida-stationlite`.)

Also see: https://github.com/EIDA/mediatorws#logging-application-level

cheers

**Comment by Jollyfant** [comment]
There is no logging of the `500` it seems. Log level should be on DEBUG. Anyway I'm gonna retire for today. Thanks 4 the help.

    [Wed Jul 18 14:34:50.737112 2018] [wsgi:error] [pid 22:tid 139756230870784] <EIDA> 2018-07-18T14:34:50+0000 INFO root 22 app.py:199 - Using logging configuration read from "/var/www/mediatorws/config/logging.conf"
    [Wed Jul 18 14:34:50.738310 2018] [wsgi:error] [pid 22:tid 139756230870784] <EIDA> 2018-07-18T14:34:50+0000 INFO root 22 app.py:142 - Serving with mod_wsgi.

**Comment by damb** [comment]
@Jollyfant,

there must be a configuration issue. I tested just now -> `Exceptions` are logged (loglevel is `CRITICAL`). Even when using `mod_wsgi`.

The configuration is as follows:

`/var/www/stationlite/config/eidangws_config`:
```
[CONFIG_STATIONLITE]
# Configuration section for the EIDA StationLite Webservice. Note, that
# commandline parameters passed is given priority over options set within this
# file. The syntax for option setting is:
#
# key=value
#
# You obtain additional information as well as default configuration values
# when entering:
#
# $ eida-stationlite --help
#
# See also the Python configparser module documentation:
#   - https://docs.python.org/library/configparser.html
#
# -----------------------------------------------------------------------------
# Start the application by means of the local Flask WSGI server.
# (default: False)
#
# start_local={True,False}
# ----
# Set the port number the local Flask WSGI server is serving. Note, that this
# parameter is taken only into consideration if start_local=True.
#
# port=PORT
# ----
# DB URL indicating the database dialect and connection arguments. For SQlite
# only a absolute file path is supported.
# See also:
# http://docs.sqlalchemy.org/en/latest/core/engines.html#database-urls
#
# db_url = sqlite:////abs/path/to/stationlite.db
db_url = sqlite:////var/www/stationlite/db/stationlite.db
# ----
# Set the path to a logging configuration file. For information on howto setup
# a logging configuration file visit the official Python documentation:
# https://docs.python.org/3/library/logging.config.html#configuration-file-format
#
# path_logging_conf=/path/to/logging.conf
path_logging_conf=/var/www/stationlite/config/syslog.conf
#

```

`/var/www/stationlite/config/syslog.conf`:
```
[loggers]
keys=root

[handlers]
keys=syslogHandler

[formatters]
keys=ServiceFormatter

[logger_root]
level=DEBUG
handlers=syslogHandler

[handler_syslogHandler]
class=handlers.SysLogHandler
level=DEBUG
formatter=ServiceFormatter
args=('/dev/log', 'local0')

[formatter_ServiceFormatter]
format=<STL> %(asctime)s %(levelname)s %(name)s %(process)d %(filename)s:%(lineno)d - %(message)s
datefmt=%Y-%m-%dT%H:%M:%S%z
```

Next, I configured `rsyslog`. See the instructions in the [eida-stationlite.conf.rsyslog](https://github.com/EIDA/mediatorws/blob/master/config/eida-stationlite.conf.rsyslog).

Did you read http://modwsgi.readthedocs.io/en/develop/user-guides/debugging-techniques.html? I strongly recommend you to use a [SyslogHandler](https://docs.python.org/3/library/logging.handlers.html#sysloghandler).

cheers

**Comment by damb** [comment]
@Jollyfant,
FYI. I commited a copy-paste error within the VirtualHost configuration (see: https://github.com/EIDA/mediatorws/issues/37#issuecomment-405515130). Now, it should be correct.

cheers

**Comment by Jollyfant** [comment]
Yeah, no problem. Thanks for updating the comment.

**Comment by Jollyfant** [comment]
Ok I got this thing running :fireworks:

It still tries to connect to `mediator-devel.ethz.ch` instead of localhost despite that I have configured settings.py. Is this not dynamically loaded in WSGI?

**Comment by damb** [comment]
Regarding dynamically loading:
  - Did your reinstall the services after changing `settings.py`?
  - The services are set up using a [WSGIDeamonProcess](https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html). Perhaps there is a configuration option, providing dynamical loading of the application.
  
Personally, after changing the source code I restart Apache.

e45f265a667f18986874e0af8e4837509466fdfe contains the URL fix. However, it is still not part of master.

**Comment by Jollyfant** [comment]
Can we merge it? The Docker container when built pulls from `master`, otherwise I will have to ship the source code with the Dockerfile and make some modifications there.

**Comment by Jollyfant** [comment]
Opened a pull with a `Dockerfile` that works pretty well for now.. we can modify it from the repo.

**Comment by damb** [comment]
@Jollyfant,
there is a working docker image at [Docker Hub](https://hub.docker.com/r/damb/mediatorws/). You can download it with

```
docker pull damb/mediatorws:latest
```

In short the setup is as follows:
- `ubuntu:16.04`
- `mod_wsgi` for Python 3
- `eida-federator` and `eida-stationlite` are set up separately i.e. each service is installed into its own `venv`
- the services use Python3
- user `eida:www` is owner of the service directories under `/var/www/`; `eida:www` runs also the `mod_wsgi` deamon processes

Missing features:
- `ubuntu:18.04`
- services do not come along with configured application logging
- `eida-stationlite-harvest` is not configured using `cron`

After running the container from the image initially fill the `eida-stationlite` DB. Login into the the container, get a shell and invoke:

```
su eida -
cd /var/www/stationlite
. venv3/bin/activate
eida-stationlite-harvest --logging-conf config/logging.conf sqlite:////var/www/stationlite/db/stationlite.db
```

Harvesting takes some time.

I'm going to add a note to the README file.

**BTW**: Due to configuration purposes I already had a working [ansible](https://www.ansible.com/) playbook. Hence, I used [ansible-container](https://www.ansible.com/integrations/containers/ansible-container) to create a docker image. To provide a container image including the missing features mentioned above I'd have to create a *conductor image* based on e.g. https://github.com/phusion/baseimage-docker (:+1: @andres-h).

cheers

**Comment by damb** [comment]
There is no `Dockerfile`. I exclusively have the playbooks from `ansible`. Then, I use `ansible-container` to create the image.

>```
>docker exec <container_name> eida-stationlite-harvest sqlite:////var/www/stationlite/db/stationlite.db
>```

Good point. However, you have to use `eida-stationlite-harvest` from virtual environment. Hence

```
docker exec <container_name> /var/www/stationlite/venv3/bin/eida-stationlite-harvest sqlite:////var/www/stationlite/db/stationlite.db
```

**Comment by Jollyfant** [comment]
Ok that works, so only logging is still a problem. `docker logs` will show anything printed to `stderr` and `stdout`. Is it an idea to use a `StreamHandler` instead of `SysLogHandler`? Or do you prefer to set up the syslog anyway? It's possible to have another container dedicated to logging, and let this image write to there I suppose.

**Comment by damb** [comment]
> Ok that works, so only logging is still a problem. docker logs will show anything printed to stderr and stdout. Is it an idea to use a StreamHandler instead of SysLogHandler?

This might be worth trying. However, we should check how `mod_wsgi` behaves when logging to `stdout` and `stderr` within a container. If it works fine we could configure the container with e.g. a [Syslog logging driver](https://docs.docker.com/config/containers/logging/syslog/).

For production I'd prefer and recommend a proper configuration i.e. either with [baseimage-docker](https://github.com/phusion/baseimage-docker) or even with a separate logging container (as you already mentioned).

**Comment by Jollyfant** [comment]
The one you posted doesn't use baseimage-docker?

**Comment by damb** [comment]
Nope (currently it is `ubuntu:16.04`.). This is due to the fact that there is no `baseimage-docker` `ansible-container` *conductor image* available. I'd have to set it up on my own, which is possible, but I first wanted `Apache` + `mod_wsgi` + `eida-{federator,stationlite}` to be working.

**Comment by damb** [comment]
I pushed a new image to [Docker Hub](https://hub.docker.com/r/damb/mediatorws/). It is now based on `baseimage-docker`.

* `eida-stationlite-harvest` is now configured using `cron`

 A configured application logging is still missing. Now, we could use `syslog-ng` internally ...

**Comment by damb** [comment]
Closed. Discussion about a proper application logging setup is continued in #39.
