### ISSUE TITLE
fed, stl: Configuration (Docker): Logging

### ISSUE THREAD

**Issue by damb** [EIDA/mediatorws#39]
Continued discussion about a proper application logging setup.

**Comment by damb** [comment]
@Jollyfant,

`syslog-ng` is a system logger facility similar to `rsyslog` (see e.g. the gentoo wiki on [syslog-ng](https://wiki.gentoo.org/wiki/Syslog-ng) and [rsyslog](https://wiki.gentoo.org/wiki/Rsyslog)). `syslog-ng` already ships with `baseimage-docker` (https://github.com/phusion/baseimage-docker#logging) and 

> Syslog messages are forwarded to the console.

Hence, still on top you might use the `ELK` stack. (I've no clue which approach *EIDA* is implementing. Maybe you know can tell me more about it.)

Logging seems to be quite an advanced topic when using  a container infrastructure and there are several ways to go. Moreover, it depends on the infrastructure you have already implemented.

**Comment by Jollyfant** [comment]
> Hence, still on top you might use the ELK stack. (I've no clue which approach EIDA is implementing. Maybe you know can tell me more about it.)

Logging is very muddy at the moment because nothing has been agreed on by the ETC. And we're running a collection of random tools without any coherent infrastructure.. ODC and RESIF are both trying to work with `ELK`. This (https://github.com/deviantony/docker-elk) works very well since logstash & ES are pretty liberal in what they accept.

**Comment by damb** [comment]
Ok. What do you think of the following approach?: First we discuss the topic by the ETC. Then we implement a proper (ideally coherent) solution.

Depending on the outcome our most recent container images should be flexible enough to be extended.

**Comment by Jollyfant** [comment]
Yeah, okay.

**Comment by damb** [comment]
Implemented with ebf528666e7a8be5664fff2bdb66a0c2e554c72d. @Jollyfant, decided to go for a file based setup using a [TimedRotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.TimedRotatingFileHandler). Closing.
