### ISSUE TITLE
fed: No response for network 4C

### ISSUE THREAD

**Issue by greg-FR13** [EIDA/mediatorws#41]
Hi All,

We are still testing eida-federator, with the following request firefox does not return a result or response.

http://federator-testing.ethz.ch/fdsnws/dataselect/1/query?network=4C&starttime=2011-10-23T20:00:00&endtime=2011-10-23T20:02:00

But it is working for all the others nodes.

For example at RESIF and GFZ :

http://ws.resif.fr/fdsnws/dataselect/1/query?network=4C&starttime=2011-10-23T20:00:00&endtime=2011-10-23T20:02:00

http://geofon.gfz-potsdam.de/fdsnws/dataselect/1/query?network=4C&starttime=2011-10-23T20:00:00&endtime=2011-10-23T20:02:00

Could you please have a look ?

Thank you,

Best,

Rima
Gregory

**Comment by damb** [comment]
Hi @greg-FR13,

when requesting routes from
```
http://federator-testing.ethz.ch/eidaws/routing/1/query?network=4C&starttime=2011-10-23T20:00:00&endtime=2011-10-23T20:02:00
```
the result is fine.

However, the endpoints seem to have trouble serving the requests. When analyzing the logs from the `eida-federator` development server I'm observing multiple errors of type
```
<EIDA> 2018-08-09T16:55:02+0000 WARNING flask.app.federator.request_processor_raw 12747 process.py:252 - Result(status=u'RequestsError', status_code=503, data="HTTPConnectionPool(host='webservices.ingv.it', port=80): Max retries exceeded with url: /fdsnws/dataselect/1/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff468303310>: Failed to establish a new connection: [Errno 111] Connection refused',))", length=280, warning=<class 'eidangservices.utils.request.RequestsError'>
```
which seems to result from *INGV* keeping `eida-federator` workers waiting. In case of `federator-testing.ethz.ch`  (PROD setup) this may lead to Apache or rather `mod_wsgi` related timeouts.

**BTW**: When exclusively requesting data from *RESIF* e.g. with:
```
fdsnws/dataselect/1/query?network=4C&sta=KES15,KES17,KES19,KES20&starttime=2011-10-23T20:00:00&endtime=2011-10-23T20:02:00
```
`federator-testing.ethz.ch` and `ws.resif.fr` serve the same data.

I'd put this issue rather into the category *EIDA endpoint configuration/optimization* (see also #35).

cheers

**Comment by damb** [comment]
Endpoint related issues were discussed at our most recent ETC meeting at Grenoble. I close this issue.
