### ISSUE TITLE
eida-federator - Spécial characters

### ISSUE THREAD

**Issue by greg-FR13** [EIDA/mediatorws#42]
Hi,

Other remark I don't know if at RESIF we are doing well but we may have special characters in descriptions field for example :

Provence-Alpes-CÃ´te d'Azur
VS
Provence-Alpes-Côte d'Azur

eida-federator : 
http://federator-testing.ethz.ch/fdsnws/station/1/query?station=REVF&minlatitude=42&maxlatitude=44&minlongitude=6&maxlongitude=8&format=text&network=FR

#Network|Station|Latitude|Longitude|Elevation|SiteName|StartTime|EndTime
FR|REVF|43.740000|7.367500|700.0|Fort de La Revere, 06059 Eze, Alpes-Maritimes, Provence-Alpes-CÃ´te d'Azur, France|2003-08-06T00:00:00|2500-12-31T23:59:59

At RESIF :
http://ws.resif.fr/fdsnws/station/1/query?station=REVF&minlatitude=42&maxlatitude=44&minlongitude=6&maxlongitude=8&format=text&network=FR

#Network|Station|Latitude|Longitude|Elevation|SiteName|StartTime|EndTime
FR|REVF|43.740000|7.367500|700.0|Fort de La Revere, 06059 Eze, Alpes-Maritimes, Provence-Alpes-Côte d'Azur, France|2003-08-06T00:00:00|2500-12-31T23:59:59

Could you please have a look ?

Thank you,

Best,

Rima
Gregory

**Comment by damb** [comment]
Hi @greg-FR13,

which kind of client are you using? When requesting data with `curl` I obtain
```
$ curl -v --output - "http://federator-testing.ethz.ch/fdsnws/station/1/query?station=REVF&minlatitude=42&maxlatitude=44&minlongitude=6&maxlongitude=8&format=text&network=FR"
*   Trying 129.132.144.214...
* TCP_NODELAY set
* Connected to federator-testing.ethz.ch (129.132.144.214) port 80 (#0)
> GET /fdsnws/station/1/query?station=REVF&minlatitude=42&maxlatitude=44&minlongitude=6&maxlongitude=8&format=text&network=FR HTTP/1.1
> Host: federator-testing.ethz.ch
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 09 Aug 2018 15:27:19 GMT
< Server: Apache/2.4.29 (Ubuntu)
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< Content-Type: text/plain
< 
#Network|Station|Latitude|Longitude|Elevation|SiteName|StartTime|EndTime
FR|REVF|43.740000|7.367500|700.0|Fort de La Revere, 06059 Eze, Alpes-Maritimes, Provence-Alpes-Côte d'Azur, France|2003-08-06T00:00:00|2500-12-31T23:59:59
* Connection #0 to host federator-testing.ethz.ch left intact
```

The result seems to be fine. (My locale is `en_US.UTF-8`).
