### ISSUE TITLE
Parsing arguments on eida-federator 

### ISSUE THREAD

**Issue by bouazzouz** [EIDA/mediatorws#43]
Hi all,

  we have  questions on  the parsing of the arguments of the fedetaror :
    1-  does the federator parse the arguments before forwarding the requests the the nodes ?
    2-  if yes, are the fdsn specifications for station and dataselect respected ?

  and about 'exit code' of the federator. Do you have  any documentation ?
Below, two queries tested by our script developed to  test federator and compare results.
It is available here : https://github.com/resif/ws-eida-test

1/ query with an error in parameter  **chanel**

    |-----EIDA:
    |    Query:  http://federator-testing.ethz.ch/fdsnws/dataselect/1/query?starttime=2004-12-23T00:00:00&endtime=2004-12-23T00:01:00&chanel=LHZ ...
    |    Status code : **200**
    |    Request duration time : 11.879999999888241
    |-----RESIF:
    |    Query:  http://ws.resif.fr/fdsnws/dataselect/1/query?starttime=2004-12-23T00:00:00&endtime=2004-12-23T00:01:00&chanel=LHZ ...
    |    Status code : **400**
    |    Request duration time : 0.019999999552965164
    |    Comparaison  not possible if code status is  different to 200

... RESIF does not accept 'chanel', and retuns 400, but the is data for this request whith 'channel' (and chanel is not in the spec)

2/ Query with a wrong parameter (toto):

    |-----EIDA:
    |    Query:  http://federator-testing.ethz.ch/fdsnws/dataselect/1/query?toto=_ALPARRAY_FR&channel=H??&starttime=2016-10-01T00:00:00&endtime=2016-10-02T00:00:00 ...
    |    Status code : **200**
    |    Request duration time : 114.30000000074506
    |-----RESIF:
    |    Query:  http://ws.resif.fr/fdsnws/dataselect/1/query?toto=_ALPARRAY_FR&channel=H??&starttime=2016-10-01T00:00:00&endtime=2016-10-02T00:00:00 ...
    |    Status code : **400**
    |    Request duration time : 0.019999999552965164
    |    Comparaison  not possible if code status is  different to 200

Thanks

**Comment by damb** [comment]
Hi @bouazzouz,

1. Yes.
2. Also yes.
 Currently we simply ignore arguments not listed within the [FDSN webservice specs](http://www.fdsn.org/webservices/FDSN-WS-Specifications-1.1.pdf). This approach is not perfect. The cleanest solution simply would be to return HTTP status code 400 (I had it already on my list) :+1:.
 The behaviour you're describing above results from ignoring `chanel` and assuming `channel=*`. Same for wrong parameters.
3) HTTP status codes: 
Currently status codes are not fully documented although `eida-federator` return codes are a subset  of the codes described at  [FDSN webservice specs](http://www.fdsn.org/webservices/FDSN-WS-Specifications-1.1.pdf).

Concretely we implement:

 | Code | Description |
 | --- | --- |
 | 200 | Ok. |
 | 204/404 | No data. |
 | 400 | Currently, exclusively when passing known query parameters with values not well-formatted. |
 | 413 | For queries which don't lead to a valid result within 600s. Even when splitting/aligning. |
 | 500 | For internal exceptions. |

cheers

**Comment by damb** [comment]
Continued at #44.
