### ISSUE TITLE
stl: Harvest restricted_status

### ISSUE THREAD

**Issue by damb** [EIDA/mediatorws#47]
While harvesting `stationlite` has to cache the stream epoch's `restricted_status=open|closed|partial` property from StationXML. Currently `eida-stationlite-harvest` does not distinguish between the stream's `restricted_status`.

The evaluation of the `restricted_status` property will be implemented *bottom-up*. I.e. if a station epoch has a `restricted_status` defined the parent's network epoch `restricted_status` value is not taken into consideration.

**Comment by Jollyfant** [comment]
> The evaluation of the restricted_status property will be implemented bottom-up. I.e. if a station epoch has a restricted_status defined the parent's network epoch restricted_status value is not taken into consideration.

A minor detail to consider: the restricted status should probably propagate down the tree if the parent restricted status is `True`. Meaning that when a network is restricted, so are all lower stations and channels. Or throw a warning that tells us there is an inconsistency in the StationXML.

**Comment by damb** [comment]
> A minor detail to consider: the restricted status should probably propagate down the tree if the parent restricted status is True. Meaning that when a network is restricted, so are all lower stations and channels. Or throw a warning that tells us there is an inconsistency in the StationXML.

@Jollyfant, a good point. Unfortunately StationXML does not specify if and how the `restrictedStatus` property propagates between StationXML `BaseNode`s. Questions arise like:
* Can a `closed` `<Network></Network>` contain `open` `<Station></Station>` epochs?
* Or vice versa i.e. is it allowed to have `closed` `<Station></Station>` epochs within an `open` `<Network></Network>`?

I popose (based on @kaestli, @javiquinte):
By default the `restrictedStatus` is `open` if undefined. If the `restrictedStatus` of a child `BaseNode` is defined it is handled with higher priority. Else I assume the `restrictedStatus` is propagated from the parent `BaseNode`.

Do you agree?

**Comment by damb** [comment]
Closed with #93.
