### ISSUE TITLE
Trailing comma in WFCatalog response

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#56]
Hi @damb, there is a trailing comma for some WFCatalog requests (e.g. NL.HGN):

    http://federator.orfeus-eu.org/eidaws/wfcatalog/1/query?station=HGN&start=2017-01-01&end=2017-01-02

For GE.APE it happens only sometimes, try refreshing a couple of times:

    http://federator.orfeus-eu.org/eidaws/wfcatalog/1/query?station=APE&start=2017-01-01&end=2017-01-02

Probably a race condition and something to do with timing since the order of channels may vary too.

https://github.com/EIDA/mediatorws/blob/1b1291d853491e49137433b944878b761e0bf8ff/eidangservices/federator/server/process.py#L887-L889

**Comment by damb** [comment]
Hi @Jollyfant,

thanks for the catch. Yes, there seems to be a racing condition while streaming `eidaws-wfcatalog` data.

However, there is no station GE.APE - at least not routed by `stationlite` @ http://federator.orfeus-eu.org. It rather is HL.APE:
```
$ curl --output - "http://federator.orfeus-eu.org/eidaws/routing/1/query?station=APE&start=2017-01-01&end=2017-01-02"
http://eida.gein.noa.gr/fdsnws/dataselect/1/query
HL APE -- HHE 2017-01-01T00:00:00 2017-01-02T00:00:00
HL APE -- HHN 2017-01-01T00:00:00 2017-01-02T00:00:00
HL APE -- HHZ 2017-01-01T00:00:00 2017-01-02T00:00:00
```

**Comment by Jollyfant** [comment]
Oh strange.. since there is also `GE.APE` but is it missing from our stationlite somehow.

http://www.orfeus-eu.org/eidaws/routing/1/query?station=APE
http://federator.orfeus-eu.org/fdsnws/station/1/query?station=APE

I will investigate why..

**Comment by damb** [comment]
> Oh strange.. since there is also GE.APE but is it missing from our stationlite somehow.
>
>http://www.orfeus-eu.org/eidaws/routing/1/query?station=APE
>http://federator.orfeus-eu.org/fdsnws/station/1/query?station=APE
>
>I will investigate why..

Did you exclude **INGV** from harvesting. When harvesting recently, `fdsnws-station` @ INGV still returned invalid StationXML. With the version currently at master `eida-stationlite-harvest` completely shuts down. This is already fixed for future releases (when `feature/auth` will be released) i.e. `eida-stationlite-harvest` exclusively does not harvest the *defect* EIDA node.

```
$ curl -v --output - "http://federator.orfeus-eu.org/eidaws/routing/1/query?net=GE"
*   Trying 145.23.3.20...
* TCP_NODELAY set
* Connected to federator.orfeus-eu.org (145.23.3.20) port 80 (#0)
> GET /eidaws/routing/1/query?net=GE HTTP/1.1
> Host: federator.orfeus-eu.org
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 204 NO CONTENT
< Date: Wed, 28 Nov 2018 12:59:16 GMT
< Server: Apache/2.4.18 (Ubuntu)
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host federator.orfeus-eu.org left intact
```

http://federator.orfeus-eu.org/eidaws/routing/1/query?net=GE returns HTTP status code 204 which most probably means that there are no routes at all currently harvested from **GFZ**.

**Comment by Jollyfant** [comment]
Nawp, let me try that.

**Comment by damb** [comment]
@Jollyfant, no race condition. It was a simple BUG. Sorry.

**Comment by Jollyfant** [comment]
Yep that did it cheers
