### ISSUE TITLE
POST Bad Request

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#6]
Hi guys, submitted this request as POST and it fails. It returns data when I query our own service. Any idea why?

request file:

    NL WTSB * BHZ 2015-01-01T00:00:00 2015-01-01T00:01:00

request:

    wget --post-file=req.txt http://mediator-devel.ethz.ch/fdsnws/dataselect/1/query
    >>> 2017-02-07 11:52:49 ERROR 400: BAD REQUEST.

Best,
Mathijs

**Comment by feuchner** [comment]
It works if you use 

    wget --post-file=req.txt --header='Content-Type:text/plain' http://mediator-devel.ethz.ch/fdsnws/dataselect/1/query

**Comment by Jollyfant** [comment]
Ok thanks! Do you think the service should use this MIME type by default?

**Comment by feuchner** [comment]
It may be a shortcoming of the Werkzeug/Flask framework I'm using that the explicit specification of the header content type is needed. Note that if using curl as download tool, the option --data-binary has to be used along with --header "Content-Type:text/plain". I'll further investigate the issue.

**Comment by damb** [comment]
Seems to work with 77cfb2a. Closed.
