### ISSUE TITLE
FDSNWS Station response invalid (level=channel)

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#62]
Hi, I noticed that channel level requests seem to return invalid stationXML. There are some fields that appear outside of the `Channel` element (`Elevation`, `Latitude`, `Longitude`, `Site`).

http://federator-testing.ethz.ch/fdsnws/station/1/query?station=ZLV4&level=channel&channel=HHZ

    <?xml version="1.0" encoding="UTF-8"?>
    <FDSNStationXML schemaVersion="1.0">
       <Source>EIDA</Source>
       <Created>2018-12-03T08:28:45.612879</Created>
       <Network code="NL" startDate="1993-01-01T00:00:00" restrictedStatus="open">
          <Description>Netherlands Seismic and Acoustic Network</Description>
          <Station code="ZLV4" startDate="1995-04-12T00:00:00" restrictedStatus="open">
             <Channel code="HHZ" startDate="2010-05-18T00:00:00" endDate="2016-06-15T11:00:00" restrictedStatus="open" locationCode="00" />
             <Channel code="HHZ" startDate="2016-06-15T11:00:00" restrictedStatus="open" locationCode="01" />
             <CreationDate>1995-04-12T00:00:00</CreationDate>
             <Elevation>2</Elevation>
             <Latitude>53.0921</Latitude>
             <Longitude>6.7533</Longitude>
             <Site>
                <Name>Zuidlaarderveen 1 niveau 4</Name>
             </Site>
             <Channel code="HHZ" startDate="1995-04-12T00:00:00" endDate="2010-05-18T00:00:00" restrictedStatus="open" locationCode="" />
          </Station>
       </Network>
    </FDSNStationXML>

**Comment by damb** [comment]
Confirmed. Validation with http://www.fdsn.org/xml/station/fdsn-station-1.0.xsd fails. It's a `<xs:sequence></xs:sequence>` - I didn't notice that.

**Comment by Jollyfant** [comment]
@damb by the way if you are checking validation against the XSD schema you will find another problem. In SeisComP3 FDSNWS Station running at some nodes there was a bug where the order of two fields `Pole` and `Zero` are swapped (also at ETH I think).

This is not a Federator problem but end node problem..

**Comment by damb** [comment]
ff6901e seems not to fix the *unordered* StationXML issue. Reopened.

**Comment by damb** [comment]
> ff6901e seems not to fix the unordered StationXML issue.

I revoke this statement. ff6901e should fix the *unordered* StationXML issue. In addition, I implemented additional unittests testing the StationXML merging procedure. With these tests we should be safe.

If you detect further problems related, simply reopen.

**Comment by Jollyfant** [comment]
Can I try to redeploy with this fix tomorrow or should I wait?

**Comment by damb** [comment]
Tagged with `v0.9.4`. Let's give it a try.
