### ISSUE TITLE
500 on multiple channel request

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#63]
The following request (because of multiple requested channels) returns a `500`.

http://federator-testing.ethz.ch/eidaws/wfcatalog/1/query?station=ZLV4&start=2018-01-01&end=2019-01-01&cha=?H?,?DF

Here is some debugging information:

    <EIDA> 2018-12-03T08:16:41+0000 CRITICAL flask.app.federator.wfcatalog_resource 9196 fdsnws.py:187 - Local Exception: <class 'ValueError'>
    <EIDA> 2018-12-03T08:16:41+0000 CRITICAL flask.app.federator.wfcatalog_resource 9196 fdsnws.py:190 - Traceback information: ['Traceback (most recent call last):\n', '  File "/var/www/federator/venv3/lib/python3.5/site-packages/federator-0.9.3rc5-py3.5.egg/eidangservices/utils/fdsnws.py", line 180, in decorator\n    return func(self, *args, **kwargs)\n', '  File "/var/www/federator/venv3/lib/python3.5/site-packages/federator-0.9.3rc5-py3.5.egg/eidangservices/federator/server/routes/wfcatalog.py", line 92, in get\n    post=False).streamed_response\n', '  File "/var/www/federator/venv3/lib/python3.5/site-packages/federator-0.9.3rc5-py3.5.egg/eidangservices/federator/server/process.py", line 181, in streamed_response\n    self._request()\n', '  File "/var/www/federator/venv3/lib/python3.5/site-packages/federator-0.9.3rc5-py3.5.egg/eidangservices/federator/server/process.py", line 796, in _request\n    routes = demux_routes(self._route())\n', '  File "/var/www/federator/venv3/lib/python3.5/site-packages/federator-0.9.3rc5-py3.5.egg/eidangservices/federator/server/process.py", line 204, in _route\n    req = (routing_request.post() if self.post else routing_request.get())\n', '  File "/var/www/federator/venv3/lib/python3.5/site-packages/federator-0.9.3rc5-py3.5.egg/eidangservices/federator/server/request.py", line 183, in get\n    params=self.payload_get, headers=self.HEADERS)\n', '  File "/var/www/federator/venv3/lib/python3.5/site-packages/federator-0.9.3rc5-py3.5.egg/eidangservices/federator/server/request.py", line 166, in payload_get\n    se_schema.dump(self._stream_epochs)))\n', '  File "/var/www/federator/venv3/lib/python3.5/site-packages/federator-0.9.3rc5-py3.5.egg/eidangservices/utils/__init__.py", line 196, in convert_sncl_dicts_to_query_params\n    raise ValueError("StreamEpoch objects provide "\n', 'ValueError: StreamEpoch objects provide multiple temporal constraints.\n']

**Comment by Jollyfant** [comment]
Actually it happens for all services (station too)

http://federator-testing.ethz.ch/fdsnws/station/1/query?sta=ZLV4&start=2018-01-01&end=2019-01-01&cha=?H?,?DF

**Comment by damb** [comment]
Confirmed.
