### ISSUE TITLE
Internal server error when stationlite is harvesting

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#65]
Hi, I am getting a `500 Internal Server` error from the `stationlite` service when the harvesting is in progress. Sqlite cannot open the database file then, apparently.

    <EIDA> 2019-01-16T15:52:59+0000 CRITICAL flask.app.stationlite.stationlite_resource 17227 fdsnws.py:252 - Traceback information: ['Traceback (most recent call last):\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1193, in _execute_context\n    context)\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 509, in do_execute\n    cursor.execute(statement, parameters)\n', 'sqlite3.OperationalError: unable to open database file\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/stationlite-0.9.4-py3.5.egg/eidangservices/utils/fdsnws.py", line 242, in decorator\n    return func(self, *args, **kwargs)\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/stationlite-0.9.4-py3.5.egg/eidangservices/stationlite/server/routes/stationlite.py", line 86, in get\n    response = self._process_request(args, stream_epochs)\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/stationlite-0.9.4-py3.5.egg/eidangservices/stationlite/server/routes/stationlite.py", line 153, in _process_request\n    maxlon=args[\'maxlongitude\'])\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/stationlite-0.9.4-py3.5.egg/eidangservices/stationlite/engine/dbquery.py", line 185, in find_streamepochs_and_routes\n    for row in query.all():\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2995, in all\n    return list(self)\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3147, in __iter__\n    return self._execute_and_instances(context)\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3170, in _execute_and_instances\n    result = conn.execute(querycontext.statement, self._params)\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 948, in execute\n    return meth(self, multiparams, params)\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement\n    compiled_sql, distilled_params\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1200, in _execute_context\n    context)\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception\n    exc_info\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 265, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 248, in reraise\n    raise value.with_traceback(tb)\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1193, in _execute_context\n    context)\n', '  File "/var/www/stationlite/venv3/lib/python3.5/site-packages/SQLAlchemy-1.3.0b1-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 509, in do_execute\n    cursor.execute(statement, parameters)\n', 'sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file [SQL: "SELECT channelepoch.channel AS channelepoch_channel, channelepoch.locationcode AS channelepoch_locationcode, channelepoch.starttime AS channelepoch_starttime, channelepoch.endtime AS channelepoch_endtime, network.name AS network_name, station.name AS station_name, routing.starttime AS routing_starttime, routing.endtime AS routing_endtime, endpoint.url AS endpoint_url \\nFROM channelepoch JOIN routing ON routing.channel_epoch_ref = channelepoch.oid JOIN endpoint ON routing.endpoint_ref = endpoint.oid JOIN service ON service.oid = endpoint.service_ref JOIN network ON network.oid = channelepoch.network_ref JOIN station ON station.oid = channelepoch.station_ref JOIN stationepoch ON station.oid = stationepoch.station_ref \\nWHERE network.name LIKE ? ESCAPE \'/\' AND station.name LIKE ? ESCAPE \'/\' AND stationepoch.latitude >= ? AND stationepoch.latitude <= ? AND stationepoch.longitude >= ? AND stationepoch.longitude <= ? AND channelepoch.channel LIKE ? ESCAPE \'/\' AND channelepoch.locationcode LIKE ? ESCAPE \'/\' AND service.name = ?"] [parameters: (\'%\', \'HGN\', -90.0, 90.0, -180.0, 180.0, \'%\', \'%\', \'station\')] (Background on this error at: http://sqlalche.me/e/e3q8)\n']

**Comment by Jollyfant** [comment]
And when I kill the harvesting process the request is finished normally.

**Comment by damb** [comment]
Thanks for the feedback.

While developing I noticed this issue already and solved it enabling the `PRAGMA journal_mode=WAL` while harvesting.

Could you please check the SQLite version?

```
$ sqlite3 stationlite.db
sqlite> select sqlite_version();
```


See: 
* https://www.sqlite.org/draft/wal.html
* https://stackoverflow.com/questions/10325683/can-i-read-and-write-to-a-sqlite-database-concurrently-from-multiple-connections

**Comment by Jollyfant** [comment]
sqlite> select sqlite_version();
3.7.17

So that should support WAL. I will try it, cheers!

**Comment by Jollyfant** [comment]
Enabled the write ahead logging.. It creates `stationlite.db`, `stationlite.db-shm`, and `stationlite.db-wal`. But there is still a `500` with the same error.

**Comment by damb** [comment]
@Jollyfant, note, that with Sqlite Version 3.22.0 (which I'm running here) there where some additional changes applied related to the WAL pragma. Do you have the possibility to upgrade? This seems to work fine.

**Comment by Jollyfant** [comment]
So I used Sqlite Version 3.22.0 to set `PRAGMA journal_mode=WAL` but that didn't work. I guess something inside the container needs to change?

**Comment by damb** [comment]
Instead of relying on SQLite with 6cf2d716f0dbae0af9da439a20f14f0f73b108e8 the docker setup falls back to Postgres.
