### ISSUE TITLE
Strange logging

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#66]
Hi, sometimes a request is logged to:

     /var/www/mediatorws/log/federator.log

and sometimes to:

    /var/www/mediatorws/log/federator.log.2019-01-15 (yesterday)

This seems to be random.. we're using the `TimedRotatingFileHandler` from as configured in the Docker container.

**Comment by damb** [comment]
@Jollyfant,

Logging to a single file from multiple processes is not supported. There is a note in https://github.com/EIDA/mediatorws#logging-application-level (put by myself :)). While one `mod_wsgi` process is still writing to the file from a previous day another `mod_wsgi` process rotated the logfile already, and thus, writes to a new logfile. This of course leads to a great mess.

Logging is quite a complex topic when doing it properly with docker. Which type of logging do you suggest in order to establish logging to be serialized?

BTW: `phusion/baseimage` provides logging facilites by means of `syslog-ng` (https://github.com/phusion/baseimage-docker#logging). Logs by default seem to be redirected to the console. Could this help somehow together with a [SysLogHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.SysLogHandler)?

**Comment by Jollyfant** [comment]
> Logging is quite a complex topic when doing it properly with docker. Which type of logging do you suggest in order to establish logging to be serialized?

I like the idea of just writing logs to a file for now. This isn't a problem that is related to Docker right since we just mount the log directory outside the container, but that WSGI has troubles with a rotating handler?

I have very little experience with `syslog` and what it can do. Are logs just sent to another central process that does the recording to file?

**Comment by damb** [comment]
> I like the idea of just writing logs to a file for now. This isn't a problem that is related to Docker right since we just mount the log directory outside the container, but that WSGI has troubles with a rotating handler?

The `eida-federator` docker images is configured in a way such that `mod_wsgi` runs several processes. Each `mod_wsgi` process runs a `eida-federator` instance. Again, each `eida-federator` instance is configured to write to one and the same file. While `eida-federator` instance X might have already rotated the logfile `eida-federator` instance Y still may log to the old file.
How a `TimedRotatingFileHandler` actually determines the time a rollover is performed depends on the implementation of the handler. Details are described [here](https://docs.python.org/3/library/logging.handlers.html#timedrotatingfilehandler).

So generally speaking: It is not a problem of `mod_wsgi`. It is a problem of logging to a single file in a multiprocessing environment. That is why there are highly configurable `syslog` servers/deamons such as `syslog-ng`, `rsyslog` to serialize (and process) log messages.

What you actually can do with a `syslog` daemon is out of scope, here. In short, a `syslog` deamon has plenty of input channels, processes the messages and writes the output to one of its output channels (which might be a file). If you are interested:
* https://www.rsyslog.com/
* https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide

**Comment by damb** [comment]
> I like the idea of just writing logs to a file for now. 

@Jollyfant, since it is a (documented) misconfiguration I'll close this issue for now. As soon as we configure application logging within the docker container correctly we should reopen this ticket again.

**Comment by damb** [comment]
> So to get this straight, logging to a file is impossible with the current set up?

In a multiprocessing environment there is always the need to queue log messages. With the current `eida-federator` setup `syslog` for sure would be one solution to achieve this goal.

> This could be done within the container or outside, but I would prefer to keep the Federator (and any software) self-contained.

With https://github.com/phusion/baseimage-docker/ a self-contained (i.e. both within and outside) application logging setup should be feasible. However, this would require to adjust [syslog-ng.conf](https://github.com/phusion/baseimage-docker/blob/master/image/services/syslog-ng/syslog-ng.conf) of the baseimage.

Currently i.e. for a single `eida-federator` instance up and running the self-contained approach should work. But we should bear in mind that it does not scale at all. Which approach to be chosen for multiple `eida-federator` instances - multiple `eida-mediator` instances etc.? 
For distributed service environments (such as EIDA is) often an approach with a centralized logging setup is preferred. So consequently, the decision depends on EIDAs' long-term goals. 

> Then syslog could write messages from all channels to a single log file?

Yes. Writing to e.g. a single log should be configurable.
