### ISSUE TITLE
Proxy error after many minutes for station query

### ISSUE THREAD

**Issue by javiquinte** [EIDA/mediatorws#69]
We asked a user to test the framework they've been developing in the last 2 years for EPOS, but now using the Federator instead of the Routing Service and the endpoints. The first thing the software does is the following query:

http://federator.orfeus-eu.org/fdsnws/station/1/query?format=text

and gets no answer for a lot of minutes (5? 10?) and then the following error:
```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /fdsnws/station/1/query.

Reason: Error reading from remote server
```

with HTTP status code **502** returned.

**Comment by javiquinte** [comment]
I know this is most probably related to #28

**Comment by damb** [comment]
@javiquinte, after our last ETC meeting I developed a bulk request solution for `fdsnws-station?format=text|xml`. Endpoint requests are made on a network level granularity. If I remember correctly we gain some performance (unfortunately I've no numbers due to the lack of a proper system testing setup), but loose the ability to implement granular (stream level based) logging facilities for such endpoint requests.

The implementation lives in branch https://github.com/EIDA/mediatorws/tree/feature/fdsn-station-bulk. (I'd have to check how much work it would mean to catch up with the current `master`.)

**Comment by damb** [comment]
@Jollyfant, the scenario described by @javiquinte is reproducible. However, it is quite interesting that the query:

http://federator-testing.ethz.ch/fdsnws/station/1/query?format=text

returns a response (even it is quite slowly; as already described within #28). So apparently, there is another issue with the configuration of `http://federator.orfeus-eu.org`. @Jollyfant, could you check, what's going wrong here? Thanks.

**Comment by Jollyfant** [comment]
There's a possibility our proxy doesn't stream the data when it is received but waits for the full request to finish (which takes long). Is your service behind `mod_proxy` too?

http://federator-testing.ethz.ch/fdsnws/station/1/query?format=text

**Comment by Jollyfant** [comment]
The request to stationlite seems to take very long and will time out the proxy. But when I do a direct request all routes it finishes in roughly 40 seconds.

    curl "http://stl:8080/eidaws/routing/1/query"

Also our service is dying under this request and it is not killed when the clients hangs up.

    33 www-data  20   0 2336536  86692   6580 S  98.3  0.7   2:28.87 apache2                                               
    39 www-data  20   0 1299132  60348   6576 S  97.7  0.5   2:41.68 apache2                                               
    32 www-data  20   0 1299388  60880   6568 S  97.0  0.5   1:14.99 apache2                                               
    31 www-data  20   0 1298880  61272   6596 S  94.3  0.5  11:59.27 apache2

**Comment by damb** [comment]
> Is your service behind mod_proxy too?

Nope.

> But when I do a direct request all routes it finishes in roughly 40 seconds.

In accordance with my experience. To be improved/optimized ...

**Comment by Jollyfant** [comment]
> In accordance with my experience. To be improved/optimized ...

But it doesn't finish in 40 seconds when the request is made through the Federator like Javier is doing in this OP of this thread.

**Comment by Jollyfant** [comment]
It comes through when I query the Federator directly (not through the proxy).

    curl "http://fed:8080/fdsnws/station/1/query?format=text"

**Comment by Jollyfant** [comment]
And now it kind of works? Color me surprised..

**Comment by damb** [comment]
:)

@Jollyfant, does it work after restarting apache? Is it possible to restart the container? It would be interesting to know the details.

**Comment by Jollyfant** [comment]
Yeah I restarted the container and it worked more reliably. But I cannot reproduce this consistently right now..

**Comment by Jollyfant** [comment]
What is the ETH deployment regarding the # of threads? GFZ is returning a lot of `503 service unavailable` for this request. I am using the defaults as in the Docker config.

**Comment by damb** [comment]
> What is the ETH deployment regarding the # of threads?

The defaults.

Same for me. @andres-h ones noted that GFZ accepts 2 concurrent request threads, if I remember right.

Basically there are two solutions:
 - `eida-federator` implements EIDA node specific thread configuration
 - HTTP **5xx** is handled by e.g. retrying (as done by `fdsnws_fetch`)

Most probably, I would go for the first solution.

**Comment by Jollyfant** [comment]
Yeah the second option is not good. I think your first suggestion is a good solution to keep it flexible.

**Comment by damb** [comment]
Closed. Not relevant anymore with the most recent deployment at `eida-federator.ethz.ch`.

Without any further optimization, a granular request strategy and empty caches the service returns a response for `fdsnws-station?format=text` within `~ 10 min` (i.e. when the last chunk of data is streamed). Once backend caches are filled, it takes `< 1 min` before the entire response is returned.

The current deployment limits the number of concurrent endpoint requests by means of *bottleneck proxies*.
