### ISSUE TITLE
fed: Limiting access to EIDA DCs

### ISSUE THREAD

**Issue by damb** [EIDA/mediatorws#70]
Some EIDA nodes except only a restricted number of concurrent download threads.

That is why, `eida-federator` should allow an EIDA node specifc thread configuration. Even better: A resource specific thread configuration.

**Comment by damb** [comment]
In order to limit the number of concurrent connections to an EIDA DC we agreed on using a distributed [Semaphore](https://en.wikipedia.org/wiki/Semaphore_(programming)) (counting). Though, limiting access to EIDA DCs implies that access might be temporarily blocked.

@kaestli, are you happy with a simple timeout solution (i.e. wait for `XX` seconds until a *connection slot* is available, again; if the timeout expired, then drop the request) for the time being?

**Comment by kaestli** [comment]
Well, a queue would be more efficient (no wait time while a connection would already be free, but the next polling request is not in). But i know it is not feasible with all our current optimizations for parallel processing.
-> let us do this for the time being. As answering the poll is fast and lightweight, we can keep polling intervals short (fractions of seconds)

**Comment by damb** [comment]
Fixed at https://github.com/damb/eidaws. Access limitation is implemented by means of *bottleneck proxies*.
