### ISSUE TITLE
Adding X-Forwarded-For to HTTP request headers

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/mediatorws#71]
The user IP should be forwarded to the endpoint through the appropriate HTTP header. I am not sure of the easiest way to propagate the address all the way down to `RequestHandlerBase`.

**Comment by Jollyfant** [comment]
From http://flask.pocoo.org/docs/1.0/reqcontext/ I assume it can be as simple as adding.. 

    from flask import request
    print(request.remote_addr)

**Comment by Jollyfant** [comment]
Started this in #73

**Comment by damb** [comment]
Fixed at https://github.com/damb/eidaws. The original client IP is forwarded to endpoints using the `X-Forwarded-For` HTTP header field.
