### ISSUE TITLE
HTTP status code 422 on Schema validation errors

### ISSUE THREAD

**Issue by damb** [EIDA/mediatorws#9]
*federator* returns HTTP status code 422 on validation errors:

```
damb@ansilta:~/tmp$ wget -O data -v "http://localhost:5000/fdsnws/dataselect/1/query?start=2017-01-01&end=2017-01-02T12:12:12&cha=LH?&sta=BFO,DAVOXa"
--2017-12-08 16:34:37--  http://localhost:5000/fdsnws/dataselect/1/query?start=2017-01-01&end=2017-01-02T12:12:12&cha=LH?&sta=BFO,DAVOXa
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:5000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:5000... connected.
HTTP request sent, awaiting response... 422 UNPROCESSABLE ENTITY
2017-12-08 16:34:37 ERROR 422: UNPROCESSABLE ENTITY.
```

**Comment by damb** [comment]
Will be fixed as soon as we focus on logging/exception handling.

**Comment by damb** [comment]
See also:
* https://github.com/sloria/webargs/issues/19
* https://github.com/sloria/webargs/blob/dev/examples/flaskrestful_example.py

**Comment by damb** [comment]
The discussion regarding error/exception handling will continue at #21.

**Comment by damb** [comment]
Duplicate of #21.

**Comment by damb** [comment]
Webservices should abort and return HTTP status code 400 for improper formated query e.g.

```
$ wget -O - "http://mediator-devel.ethz.ch/fdsnws/station/1/query?foo=--&minlat=48&maxlat=49&net=GR&service=station&format=text"
```

Currently unknown request parameters are ignored and the request is processed as

```
$ wget -O - "http://mediator-devel.ethz.ch/fdsnws/station/1/query?minlat=48&maxlat=49&net=GR&service=station&format=text"
```

Check [webargs](https://github.com/sloria/webargs) to implement a proper solution.

**Comment by damb** [comment]
Implemented with 77cfb2a. In addition, also `stationlite` provides a *nodata* query parameter. `eidaws-wfcatalog` however still uses exclusively HTTP status code 204. @Jollyfant : Did you ever think about adding the *nodata* query parameter to `eidaws-wfcatalog`?

**Comment by Jollyfant** [comment]
Hi @damb, have considered it but probably won't implement it. IMO 204 is always the appropriate status code for no content.

**Comment by kaestli** [comment]
(also it is not part of the wfcatalog specification v. 0.22)

**Comment by damb** [comment]
Hi @Jollyfant,

ok thanks, that's fine for me. I read the specs. I just was wondering why it's not part of it.
