### ISSUE TITLE
EIDA node for Norway

### ISSUE THREAD

**Issue by kaestli** [EIDA/mediatorws#95]
The Norwegian EIDA node is officially approved now.

Service URLs ready to be added:

station: http://eida.geo.uib.no/fdsnws/station/1/
dataselect: http://eida.geo.uib.no/fdsnws/dataselect/1/
wfcatalog: http://eida.geo.uib.no/eidaws/wfcatalog/1/
local routes: http://eida.geo.uib.no/eidaws/routing.xml

**Comment by damb** [comment]
Thanks. I'm going to add it after christmas.

Actually, only the URL to the routing-service's `localconfig` would have been required.

**Comment by kaestli** [comment]
http://eida.geo.uib.no/eidaws/routing.xml
this is the "localconfig" of a datacenter not running the routing service (in my understanding of the routing documentation, the path of the file containing the routes is not specified in such a case. I had to ask for it.

**Comment by damb** [comment]
Closed with PR #103.
