### ISSUE TITLE
INGV vs. (default) includeavailability=false

### ISSUE THREAD

**Issue by kaestli** [EIDA/mediatorws#96]
Federator requests to endpoints include default parameters explicitly.
INGV does not support the includeavailability parameter (cfr. http://webservices.ingv.it/fdsnws/station/1/application.wadl) and answers queries containing it with http 400: " bad request due to [...] unrecognized parameter "
FDSNws-station specification says (page 2): "the service shall accept requests formulated the parameters identified in table 1" (with table 1 containing also the optional parameters).
Unclear what this should imply: should an optional, unsupported parameter be answered with http 400, or should it be accepted with http 200/204, but ignored?

**Comment by kaestli** [comment]
(comment: e.g. INGV and RESIF, according to their wadl, both don't support "includeavailability", but RESIF silently ignores the parameter, while INGV answers queries containing it with http 400)

**Comment by damb** [comment]
Not to forget about the `matchtimeseries` query filter parameter for `/fdsnws/station`.

**Comment by kaestli** [comment]
Federator (as well as any fdsnws endpoints) should follow a (yet to be issued) more detailed specification / recommendation by FDSN in the handling of unsupported parameters.

**Comment by damb** [comment]
References #100.

**Comment by damb** [comment]
PR #101 will close this issue. Reopen if required.
