### ISSUE TITLE
Frontend cache does not consider level parameter

### ISSUE THREAD

**Issue by kaestli** [EIDA/mediatorws#99]
e.g.,

http://mediator-devel.ethz.ch/fdsnws/station/1/query?net=Z3&sta=*&channel=HHE,HHN&format=xml&nodata=404
(default level = station), followed by 
http://mediator-devel.ethz.ch/fdsnws/station/1/query?net=Z3&sta=*&channel=HHE,HHN&level=response&format=xml&nodata=404
, will return twice the same station level xml, second time from cache.

In contrary, a response level query not preceded by a (otherwise identical) station level query, will return correct response level xml

(and vice versa)

**Comment by damb** [comment]
This issue refers to #97.

**Comment by damb** [comment]
Fixed at PR #97.
